bower.json
demos/src/demo.js
demos/templates/index.html
main-client.js
main.js
main.scss
src/client/bottom-slot.js
src/client/index.js
src/client/next-messaging-guru-client.js
src/client/utils.js
src/components/index.js
src/components/invite-colleagues/main.js
src/components/invite-colleagues/main.scss
src/presenters/slot-presenter.js
templates/components/n-messaging-banner.html
templates/partials/bottom/b2b-upsell.html
test/smoke.js

Add actual message components

---

Makefile
demos/app.js
demos/templates/index.html
manifest.js
src/client/bottom-slot.js
src/client/index.js
src/client/next-messaging-guru-client.js
src/presenters/slot-presenter.js
templates/slot.html

add guru integration and a local-guru-demo mode

---

Makefile
demos/app.js
demos/proxy-controller.js
demos/templates/index.html
package.json
src/client/index.js
src/client/next-messaging-guru-client.js
templates/slot.html

refactor how demo mode and guru host switching works

---

bower.json

to fix failing build on `next-article`. I'll come back and tidy up in a min :)

bump o-share

---

src/client/bottom-slot.js
src/client/index.js
src/client/utils.js
src/presenters/slot-presenter.js
templates/slot.html

add more data to the event context to help with analytics

---

manifest.js
templates/partials/bottom/payment-failure.html

add simple payment failure message

---

src/client/bottom-slot.js

fix act tracking

---

templates/components/n-alert-banner.html

Adds grid to align text

---

manifest.js
src/components/index.js
test/smoke.js

update manifest and app banner message name

---

bower.json

bumbed-n-alert-banner-version

---

Makefile
package.json
src/handlebars-helpers/nMessagingPresenter.spec.js
test/handlebars-helpers/nMessagingPresenter.test.js

Wanted to get thoughts on -
1. Completeness of tests
2. Having tests close to code rather than in a test folder
🐿 v2.7.0

Writing inital tests for nMessagingPresenter

---

templates/partials/top/anon-subscribe-now-teal.html

Append anon sub banner to ID available on all pages

---

templates/components/n-messaging-banner.html

Changes class back to n-messaging-banner__

---

manifest.js
templates/partials/top/registration-notice.html

Initial registration notice

---

demos/app.js
demos/templates/layouts/custom-vanilla.html
src/components/ad-blocker-reg-banner/main.js
src/components/ad-blocker-sub-banner/main.js

it works! 😀 
updated demo to mimic `n-counter-add-blocking` logic (which adds '`isAdBlocking` class to `html`) and logic to look for it

More ad blocking logic

---

bower.json
main.scss
manifest.js
src/components/index.js
src/components/nav-contact-preferences/main.js
src/components/nav-messaging-tooltip.scss
src/components/nav-myft/main.js
src/presenters/slot-presenter.js
templates/partials/top/nav-contact-preferences.html
templates/partials/top/nav-my-ft.html
templates/slot.html

- for core users, show message bar (server-rendered)
- for enhanced users on viewports < M, show message bar with close button
- enhanced users on wider viewports get the tooltip only
🐿 v2.8.0

Support tooltips; show fallback message for core users

---

main.scss
src/components/index.js

🐿 v2.8.0
Sorry forgot to delete this code

Removes adBlockerSubBanner and adBlockerRegBanner

---

bower.json
main.scss
manifest.js
package.json
src/components/cookie-consent/main.js
src/components/cookie-consent/main.scss
src/components/index.js
templates/partials/bottom/cookie-consent.html
test/smoke.js

Cookie consent bottom banner

---

bower.json
src/components/cookie-consent/main.js
templates/partials/bottom/cookie-consent.html

Fixing the js not working when in app

---

src/components/cookie-consent/main.js
src/components/cookie-consent/main.scss

Let cookie banner work out its display before making fixed

---

src/components/cookie-consent/main.js
src/components/cookie-consent/main.scss
templates/slot.html

Enable banner to be sticky with a fixed fallback

---

src/client/bottom-slot.js
src/client/top-slot.js
src/components/cookie-consent/main.js

Foreach not polyfilled for nodelist in IE11

---

bower.json
package.json
src/components/cookie-consent/main.js
src/components/cookie-consent/main.scss
templates/partials/bottom/cookie-consent.html

Copy updates from legal team also
🐿 v2.8.0

Localstore to cookies

---

src/components/privacy-policy/main.scss

Design tweaks to privacy policy

---

src/components/cookie-consent/main.scss

Cookie banner B below M viewport flush to bottom

---

main.scss
src/components/privacy-policy/main.scss

Remove privacy policy styles from main stylesheet as already in critical; increase specificity of privacy policy styles
🐿 v2.8.0

Fix FOUC in privacy policy message

---

src/components/cookie-consent/main.js
templates/partials/bottom/cookie-consent.html

Add cookie consent endpoint and update copy

---

templates/partials/bottom/cookie-consent.html

Copy updates from legal

---

src/components/cookie-consent/main.js

Handle this cookie via the endpoint now

---

src/components/cookie-consent/main.js

Ensure we can set cookies via ajax

---

templates/partials/bottom/cookie-consent.html

Open cookie policy link in new window

---

templates/partials/bottom/cookie-consent.html

Update tracking tag on cookie banner

---

src/client/top-slot.js
src/components/team-trial/main.js
templates/components/n-alert-banner.html
templates/partials/top/registration-notice.html

Cleaning up, fixing team trials

---

src/presenters/slot-presenter.js
templates/partials/bottom/cookie-consent.html
templates/slot.html

Also, change redirect from cookie banner
🐿 v2.8.0

Make all @root variables available to slot presenter

---

manifest.js
templates/partials/top/usa-sale.html

Adding usa sale top banner

---

src/components/index.js
src/components/marketingPopupPrompt/main.js

Adds text below the bottom button

---

src/components/top/anon-subscribe-now-teal/main.js

Adds messageElement

---

demos/templates/partials/o-header.html

Changes `my account` to `account settings` in demo

---

manifest.js
templates/partials/top/tls-deprecation.html

Banner is no longer in use.  
🐿 v2.8.0

Removes tls deprecation banner

---

templates/partials/top/team-trial.html

🐿 v2.9.0
Field populating when inspected (locally via demo)

added cpc value as query param

---

manifest.js
secret-squirrel.js
templates/partials/bottom/usa-sale.html

Adds USA bottom banner template

---

templates/components/n-alert-banner.html
templates/partials/top/nav-account-settings.html
templates/partials/top/payment-failure.html
templates/partials/top/team-trial.html
templates/partials/top/usa-sale.html

Changes content variable to contentDetail

---

templates/partials/bottom/invite-colleagues.html

Updating share link for Hong Kong campaign

---

templates/partials/bottom/invite-colleagues.html

Sets render open to true

---

templates/partials/bottom/invite-colleagues.html

Updating the copy for hong kong

---

secret-squirrel.js

Removing old secret

---

bower.json
manifest.js
package.json
templates/components/n-messaging-banner.html
templates/partials/bottom/app-promoting-banner.html
templates/partials/bottom/swg-entitlements-prompt.html
templates/partials/top/usa-sale.html

🐿 v2.10.3
Removing old sale info from top banner - for card https://trello.com/c/KKmCLgqT

remove usa sale top banner

---

main.scss

🐿 v2.10.3
This was breaking the demo

Removed forgotten SCSS import

---

main.scss

Don't import `./src/components/bottom/swg-entitlements-prompt/main.scss` as it aint there
🐿 v2.10.2

Don't import `./src/components/bottom/swg-entitlements-prompt/main` as it aint there   🐿 v2.10.2

---

templates/partials/bottom/book-your-consult.html

Book your consult message, Spell corrected
🐿 v2.10.3

Book Your Consult

---

main.scss
manifest.js
src/components/bottom/brexit/main.scss
templates/partials/bottom/brexit.html

Trello card: https://trello.com/c/7eLNV92u
Image:

Add brexit campaign

---

src/components/bottom/brexit/main.scss
templates/partials/bottom/brexit.html

Update message and ensure the styles are contained

Update Brexit message

---

secret-squirrel.js
templates/partials/bottom/brexit.html

https://trello.com/c/O71Rkm1D/969-brexit-campaign-add-tracking-to-link-in-onsite-message
🐿 v2.12.0

Add segementId to products link in Brexit message

---

manifest.js
secret-squirrel.js

Update offer ID on marketing pop prompt

---

secret-squirrel.js
templates/partials/top/anon-subscribe-now.html

Update anon subscriber banner link with different tracking

---

manifest.js

Added b2bTrialAnon Component

---

manifest.js
secret-squirrel.js
templates/partials/bottom/content-message.html

Add generic message for population with content later
🐿 v2.12.3

Add content message

---

manifest.js

New lazy messages added

---

manifest.js
src/components/top/gift-articles/main.js
src/components/top/my-ft-feedpage/main.js
templates/partials/bottom/ft-weekend-promo.html
templates/partials/top/gift-articles.html
templates/partials/top/my-ft-feedpage.html

Add new messages for the NBA Envoy journey

---

secret-squirrel.js
templates/partials/bottom/content-message.html

https://trello.com/c/zaTX0zfu/1338-1trial-banner-on-specific-article

Update Trial Offer Content Message Copy

---

templates/partials/bottom/app-promo-mobile.html

Add missing attribute needed for messaging:act events to be fired

---

bower.json
manifest.js
src/components/bottom/cookie-consent/main.js
src/components/bottom/swg-entitlements-prompt/main.js
src/components/top/myft-disengaged-header-tooltip/main.js
templates/partials/top/myft-disengaged-header-tooltip.html

add myft disengaged header (move from myft-ui)

add myft disengaged header

---

src/components/top/myft-disengaged-tooltip/main.js

fix myft disengaged header function args

---

manifest.js
templates/partials/bottom/abb-licence.html

🐿 v2.12.4
This is about creating an onsite message barrier that will be shown to ABB users leading up to their licence cancellation.
[Trello ticket](https://trello.com/c/tWNVdVCs/1522-bespoke-onsite-message-for-abb-client#comment-5d835b81b27ef05c2c0906c7)

Add abb-licence message

---

templates/partials/bottom/abb-licence.html

Suppress close button on ABB licence message

---

src/components/bottom/app-promo-mobile/main.scss
templates/partials/bottom/app-promo-mobile.html

This PR is to fix the style issue on appPromoMobile OSM banner.

appPromoMobile OSM banner style issue fixed 🐿 v2.12.5

---

secret-squirrel.js
templates/partials/bottom/new-agenda.html
templates/partials/top/new-agenda.html

Add segment Ids to the URLs in the new adgenda

---

src/client/utils.js

So it has the desired effect of suppressing duplicate message display while the Spoor/Envoy pipeline catches up.
But .. does not wrongly suppress subsequent genuine attempts to show the user the same message (eg. in a second iteration of an Envoy journey).
This fix is to get us going with ftWeekendPromo message.  We'll need a broader rethink about controlling message display later on.

Limit the effect of the suppression cookie

---

src/components/bottom/my-ft-feedpage-overview/main.scss

Small tweak to styling of header on the message.

Use serif font for heading, as per the design spec 🐿 v2.12.5

---

src/components/bottom/my-ft-feedpage-overview/main.scss

to increase whitespace between button and background image on desktop view 🐿 v2.12.5

Minor styling tweak 

---

main.scss
manifest.js
src/components/bottom/fast-ft/main.scss
src/components/bottom/markets-data/main.scss
templates/partials/bottom/fast-ft.html
templates/partials/bottom/markets-data.html

Port new v4 messages into v3 branch for impatient deployment 🐿 v2.12.5
Not ready for actual PR yet... this is for Origami team to help with the backwards compatibility.

fastFt and marketsData

---

manifest.js
secret-squirrel.js
templates/partials/top/print-banner-usa.html

[Ticket](https://trello.com/c/Tr1x94AH/1681-geo-targeted-print-banner-us)

feat: USA anon print sale top banner 🐿 v2.12.5

---

src/components/top/anon-subscribe-now/main.scss
templates/components/n-alert-banner.html
templates/partials/top/print-banner-usa.html

Also add the legal copy to usPrintSale banner.

feat: add terms capability

---

src/client/top-slot.js

to resolve ES6/CJM errors in Page Kit

Adds .default to the o-message require statement

---

src/components/bottom/newsletter-promo/main.scss

It broke during Origami upgrade 🐿 v2.12.5

Fix bespoke styling for newsletterPromo 

---

src/components/top/nbe-auto-sub/main.scss

Reduce font size, change background/text color following UX design feedback 🐿 v2.12.5

 nbeAutoSub message - minor style tweak

---

manifest.js
src/client/bottom-slot.js

Missing imperative formAction added in order to render form html tag on onsite message 🐿 v2.12.5

Missing formAction added to Imperative option.

---

manifest.js
templates/partials/bottom/secondary-school-survey.html

Due to the need to change back to the old message on interaction with the survey, its easier to treat this as an alternative SSI message - targeted the same but higher priority message and strict rules about interaction. (TBD in Ammit)

feat: add new secondary school survey message 🐿 v2.12.5

---

client/components/bottom/us-election-2020-promo/main.scss
main.scss
manifest.js
server/templates/partials/bottom/us-election-2020-promo.html

New banner/messaging component to promote discounted subscriptions for the US 2020 election. 🐿 v2.12.5

Promotional banner for US 2020 election

---

server/templates/partials/bottom/us-election-2020-promo.html

A few tweaks to the US election promo banner as requested by the US B2C team.

Updates to US election promo

---

server/templates/partials/bottom/us-election-2020-promo.html

Adds query parameters for tracking purposes to the US 2020 election promo banner.

Update subscribe link on US election banner

---

client/index.js
main.scss
manifest.js
server/templates/partials/bottom/kpmg-licence.html

[Ticket](https://financialtimes.atlassian.net/browse/AC-256)
Related [`next-ammit-api` PR](https://github.com/Financial-Times/next-ammit-api/pull/646)

Add KPMG message

---

client/components/o-message-notice.scss
main.scss
manifest.js
server/templates/components/o-message-notice.html
server/templates/partials/top/coronavirus-newsletter-promo-top.html

Create a corona virus newsletter top slot message.
- The template isn't general for now but can be adapted in the future

AC-274: Create top slot corona newsletter message

---

server/templates/components/o-message-notice.html

Add data-n-messaging-component to corona message to enable tracking

---

server/templates/partials/bottom/tbyb-in-trial-subscribe.html
server/templates/partials/bottom/tbyb-post-trial-subscribe.html

Change message header from capital letter to sentence case 🐿 v2.12.6

---

client/bottom-slot.js
client/index.js
client/top-slot.js
client/utils.js
manifest.js

[Ticket](https://financialtimes.atlassian.net/browse/ACQ-101)

ACQ-101: Add custom tracking context for marketingPopupPrompt, anonSubscribeNow, and printBannerUsa

---

client/components/bottom/marketing-popup-prompt/main.scss
main.scss
manifest.js
secret-squirrel.js

Activate slider (marketingPopupPrompt) with compliant prices on article pages and stream pages and change the click-through link
https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1035&projectKey=ACQ&modal=detail&selectedIssue=ACQ-201
https://github.com/Financial-Times/next-messaging-guru/pull/84

ACQ-201: Marketing pop prompt compliant prices

---

README.md
docs/corporate-cancellation-message.md
package.json

Previously the knowledge how to do this relied on oral transfer. This is a routine task with a number of sub tasks that must be done in a specific order for the task to be completed successfully. 
This PR adds a document where the steps are clearly outlined, so that newcomers can complete this ticket without needing to hunt down what exactly needs to be done. This list also will help to ensure that all the steps are done in the correct order.

ACC-380 Create how to for corporate cancellation messages

---

server/templates/partials/top/energy-source-promo.html

Update energy source image revision

---

client/components/top/three-months-intro-price-promo/main.scss
main.scss
manifest.js
secret-squirrel.js
server/templates/partials/top/three-months-intro-price-promo.html

https://financialtimes.atlassian.net/browse/ACQ-433
Fullwidth:
Mobile devices:

[ACQ-433] Create three months intro price promo top slot message

---

client/components/top/try-full-access/main.scss

Title and screenshot say it all.
https://financialtimes.atlassian.net/browse/ACQ-707
|Before|After|
|------|----- |
|![image](https://user-images.githubusercontent.com/1168275/100209088-1f8a3480-2f12-11eb-9b28-a8ab04cff21f.png)|![image](https://user-images.githubusercontent.com/1168275/100209152-33359b00-2f12-11eb-90aa-71ec937452b4.png)|

[ACQ-707] Set try full access message content to full width

---

manifest.js
server/templates/partials/bottom/wapo-in-trial-subscribe.html
server/templates/partials/bottom/wapo-post-trial-subscribe.html

Show Washington Post trialists onsite conversion messaging
##Ticket
https://financialtimes.atlassian.net/browse/UG-251

UG-251 Wapo onsite messaging

---

client/components/bottom/cookie-consent/main.js
client/index.js
critical.scss

- Ensure the cookie message is displayed above other ft.com elements
- Initialise o-cookie-message JavaScript 
See commit messages for more details

Cookie message fixes

---

client/components/bottom/post-activation-journey/main.js
client/components/bottom/post-activation-journey/main.scss
main.scss
manifest.js
server/templates/partials/bottom/post-activation-journey.html

New message template for **Post Activation Journey** feedback popup.
https://financialtimes.atlassian.net/browse/UG-353

UG-353 — Create Post Activation Journey template

---

client/components/bottom/cookie-consent/main.js
client/components/bottom/post-activation-journey/main.js
client/index.js
demos/templates/index.html
server/templates/partials/bottom/post-activation-journey.html

We need to close the banner after a user has clicked the 'Leave Feedback'  button.

Close the banner after a user has clicked the 'Leave Feedback'  button

---

client/components/top/three-months-intro-price-promo/main.scss
manifest.js
secret-squirrel.js
server/templates/partials/top/three-months-intro-price-promo.html

Making threeMonthsIntroPricePromo a dynamic message with US/UK and CEMEA prices/messages. Previous static US threeMonthsIntroPricePromo message is now deleted.
This PR requires [next-messaging-guru #135](https://github.com/Financial-Times/next-messaging-guru/pull/135)
[ACQ-862](https://financialtimes.atlassian.net/browse/ACQ-862)
Web | Mobile
------------ | -------------
Web | Mobile
------------ | -------------
Web | Mobile
------------ | -------------

ACQ-862: Promote print subs on top slot in UK and CEMEA

---

client/components/top/three-months-intro-price-promo/main.scss

[ACQ-862](https://financialtimes.atlassian.net/browse/ACQ-862)
Requirement from Design team:
Web | Mobile
------------ | -------------
Web | Mobile
------------ | -------------
Web | Mobile
------------ | -------------

ACQ-862: Small cosmetic fix about centring the main component vertically

---

client/components/top/three-months-intro-price-promo/main.scss

More cosmetic fixes about centring the main component horizontally and increasing font size depending the screen size.
> Would we be able to centre the main objects horizontally on phone and tablet screens? Many thanks
[ACQ-862](https://financialtimes.atlassian.net/browse/ACQ-862)
Phone | Tablet | Web
------------ | ------------- | -------------

ACQ-862: More styles fixes

---

client/next-messaging-guru-client.js

This is a fix to prevent the `next-messaging-guru` request is cached when it contains only different header values.
Complete discussion at:
- Problem: https://financialtimes.slack.com/archives/CSVRXFV6F/p1616168502065900
- Troubleshooting: https://financialtimes.slack.com/archives/CSVRXFV6F/p1616402564089300
Console output after fix
```
// request for UK
proxying request URL= https://www.ft.com/__message/threeMonthsIntroPricePromo {"method":"GET","headers":{"connection":"keep-alive","sec-ch-ua":"\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\"","accept":"application/json","ft-skip-cache":"Yes","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 …
```

ACQ-862: Prevent next-messaging-guru to be cached

---

client/components/bottom/cookie-consent/main.js

[ADSDEV-777](https://financialtimes.atlassian.net/browse/ADSDEV-777)
Track the Cookies Policy `click` event.

ADSDEV-777 Track the Cookies Policy click event

---

client/components/top/digital-intro-subscription-promo/main.scss
main.scss
manifest.js

Added styles, and configured digital promo message.
https://financialtimes.atlassian.net/browse/ACQ-1069
https://github.com/Financial-Times/next-messaging-guru/pull/145
https://github.com/Financial-Times/next-ammit-api/pull/790

ACQ-1069 Introduce digital promo top slot message

---

secret-squirrel.cjs
server/templates/partials/bottom/marketing-popup-prompt-sept-apac.html

The title says all you need 😄 
Tickets:
- https://financialtimes.atlassian.net/browse/ACQ-1121?focusedCommentId=533324
- https://financialtimes.atlassian.net/browse/ACQ-1123?focusedCommentId=533323

ACQ-1123: last minute changes from Marketing on CTA link.

---

server/templates/partials/bottom/marketing-popup-prompt-sept-apac.html
server/templates/partials/bottom/marketing-popup-prompt-sept-row.html

ACQ-1121: fixing styles on slider september campaign

---

server/templates/partials/bottom/marketing-popup-prompt-sept-apac.html
server/templates/partials/bottom/marketing-popup-prompt-sept-row.html

Nothing to add here....  😅 
Ticket: https://financialtimes.atlassian.net/browse/ACQ-1121

ACQ-1121: Missing closer divs on sept campaign messages.

---

server/templates/partials/bottom/marketing-popup-prompt-sept-apac.html
server/templates/partials/bottom/marketing-popup-prompt-sept-row.html

https://financialtimes.atlassian.net/browse/ACQ-1189
Updating body messages for mobile version of September Campaign Sliders

ACQ-1189: updating messages for mobile version of September Campaign

---

client/components/bottom/customer-care-call/main.js
manifest.js
server/templates/partials/bottom/customer-care-call.html

Added new template customer-care for bottom slot messages and assigned it to the activationNotStarted, activationNotComplete and activationSkipped variants replacing the current messages.
https://financialtimes.atlassian.net/browse/UG-507

UG-507: Show customer care message on customerCareCall variant

---

secret-squirrel.cjs
server/templates/partials/top/cop-open-day-climate-capital-anon.html

Changed url for Moral Money newsletter
https://financialtimes.atlassian.net/browse/ACQ-1305

ACQ-1305. Changed url for Moral Money newsletter

---

client/components/top/open-day-premium-upsell/main.scss

ACC-1241 Increase padding-bottom on upgrade to premium button

---

client/components/top/cop-open-day-anon-or-reg/main.scss
main.scss
manifest.js
server/templates/partials/top/cop-open-day-anon-or-reg.html

Ticket: https://financialtimes.atlassian.net/browse/ACQ-1291

ACQ-1291: removing 2021 COP Open Day top message

---

bower.json
main.scss
package-lock.json
package.json

Revert o-message version to what it was before open day and remove last bit of premium upsell banner.
I have tested some banners and they seem to be working.

Change o-message version

---

client/components/bottom/jan-22-digital-sale-slider/main.js
client/components/bottom/jan-22-digital-sale-slider/main.scss
client/components/top/jan-22-digital-sale-banner/main.scss
main.scss
manifest.js
secret-squirrel.cjs
server/templates/partials/bottom/jan-22-digital-sale-slider.html
server/templates/partials/top/jan-22-digital-sale-banner.html

Targeting as per this [document](https://docs.google.com/document/d/1q0t8sGs66h2p-17AC8qNZ3fwkegfA4oxDzQQ9xkMQLw/edit) 
- Campaign position 1: Top slot => The message needs to be behind top slot flag; suggested message name: `Jan22DigitalSaleBanner`.
- Campaign position 2: Slider => The message needs to be behind bottom slot flag; suggested message name: `Jan22DigitalSaleSlider`.
Designs: https://www.figma.com/file/3nYFA1aYPpRh7qC8VuNTVw/Onsite--messages?node-id=103%3A21
- https://financialtimes.atlassian.net/browse/ACQ-1374
- https://financialtimes.atlassian.net/browse/ACQ-1375
| Mobile | Desktop |
| --- | --- |
| ![Screenshot 2022-01-03 at 16 39 34](https://user-images.githubusercontent.com/13876273/147951393-e2bbd0ce-e4b8-4bde-9835-a3e5417673a1.png) | ![Screenshot 2022-01-03 at 16 40 …

ACQ-1374 and ACQ-1375: Top and bottom messages for JAN 22 campaign.

---

client/components/top/disrupted-world/main.scss
main.scss
manifest.js
secret-squirrel.cjs
server/templates/partials/top/disrupted-world.html

Creating a new "crisis" top slot message => `disruptedWorld`
Designs: https://www.figma.com/file/3nYFA1aYPpRh7qC8VuNTVw/Onsite--messages?node-id=203%3A257
Requirements: https://docs.google.com/document/d/1_GTMH5MZuDXVnrpKSxC-DgoE749u-ABW_OtSQ_au53Y/edit
https://financialtimes.atlassian.net/browse/ACQ-1487
| Desktop | Mobile |
|----|----|
| ![Screenshot 2022-03-03 at 15 56 13](https://user-images.githubusercontent.com/13876273/156590838-e82af14b-3c17-425f-b1c5-0be370b3b438.png) | ![Screenshot 2022-03-03 at 15 56 23](https://user-images.githubusercontent.com/13876273/156590896-01247594-284f-4a1b-8bef-a0b05b5b2780.png) |

ACQ-1487: A new top slot message disruptedWorld

---

client/components/bottom/embedded-onboarding/main.js
client/components/bottom/embedded-onboarding/main.scss

Removes veil set up by embeddedOnboarding template message when the homepageOnboarding flag is not active

UG-823: Remove veil from embeddedOnboarding template when homepageOnboarding flag is not active

---

manifest.js

change case of message variant

---

client/components/bottom/marketing-popup-prompt/main.scss
manifest.js

As part of changing the copy of the bottom slider, we found some inconsistencies in the typography.
This PR fixes those
https://financialtimes.atlassian.net/browse/ACQ-1544

[ACQ-1544] Change the font of the bottom slider title && bold it

---

client/components/top/disrupted-world/main.scss
server/templates/partials/top/disrupted-world.html

Change the text on the button for #messageSlotTop variant “Disrupted World”
https://financialtimes.atlassian.net/browse/ACQ-1563

ACQ-1563: Change the text on the button for #messageSlotTop

---

manifest.js
server/templates/partials/bottom/content-message-danske-bank.html

Implement cancellation message for Danske Bank.
related PR: https://github.com/Financial-Times/next-ammit-api/pull/849
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1461?modal=detail&selectedIssue=ACC-1627&search=dansk)

ACC1627 Add Danske Bank cancellation message

---

package-lock.json
package.json

Bump up n-my-ft-ui to solve the following error on next-article

ACC1627 - Bump up n-myft-ui

---

package-lock.json
package.json

make sure we are using the latest versions

Update n-myft-ui and next-myft-client

---

server/templates/partials/bottom/content-message-danske-bank.html

[JIRA](https://financialtimes.atlassian.net/browse/ACC-1691)

ACC-1691 Revert "ACC1627 - fix typo Danske Bank message"

---

package-lock.json
package.json

[JIRA](https://financialtimes.atlassian.net/browse/ACC-1691)

ACC1691 remove n-myft-ui from devDependencies

---

package-lock.json
package.json

while I cannot find any references to x-follow-button within the code, I am updating the x-dash components just in case there is some downstream usage of it

Update x-follow-button to v8

---

manifest.js
server/templates/partials/top/cop-open-day-climate-capital-anon.html

Remove COPOpenDayClimateCapitalAnon message, moved to exponea.
Ticket: https://financialtimes.atlassian.net/browse/ACQ-1841
Relates to: https://github.com/Financial-Times/next-ammit-api/pull/864

ACQ-1841: remove COPOpenDayClimateCapitalAnon

---

client/components/bottom/cookie-consent/main.scss
main.scss
server/templates/partials/bottom/cookie-consent.html

This variant is to be used as part of an AB test to discover how the design of the cookie banner might affect our consent rate.

Adds cookie banner design variant

---

package-lock.json
package.json
server/templates/partials/bottom/cookie-consent.html

[Jira Ticket](https://financialtimes.atlassian.net/browse/ADSDEV-1205)
[origami PR](https://github.com/Financial-Times/origami/pull/858)
[advertising PR](https://github.com/Financial-Times/advertising/pull/321)

[ADSDEV] Cookie Banner fixes

---

demos/templates/index.html

Boring and know it's not a risk but let's clean up.

Remove polyfill.io reference
