Financial-Times/n-messaging-client

bower.json, demos/templates/index.html, main.scss, manifest.js, secret-squirrel.js, src/components/anon-subscribe-now-teal/main.js, src/components/anon-subscribe-now-teal/main.scss, src/components/index.js, templates/components/n-alert-banner.html, templates/partials/top/anon-subscribe-now-teal.html, test/smoke.js
Porting the anonymous subscribe now banner to the n-messaging-client. In the core experience only the button (a tag) is clickable, this is enhanced to widen the click area to the whole background image for JS users.
| original | n-messaging |
| --- | --- |
| <img width="726" alt="screen shot 2018-02-02 at 16 07 53" src="https://user-images.githubusercontent.com/1721150/35742828-a33b110e-0833-11e8-8938-f03b036d9d1c.png"> | <img width="935" alt="screen shot 2018-02-02 at 16 19 22" src="https://user-images.githubusercontent.com/1721150/35743235-e145ef0e-0834-11e8-84c2-ade27f255d11.png"> |
| Chrome | Firefox | IE | Edge | Safari |
| --- | --- | --- | --- | --- |
| Enhanced | Enhanced | Core* | Enhanced | Enhanced|
\* Seems to be an JS issue with the demo page which stops the banner from being …
=> add anon subscribe now banner

README.md, src/client/index.js, templates/slot.html
**Issue**
The message is shown on the page in the original slot location before being moved to the correct location using the client side JS. This causes an unsightly jump.
**Solution**
Hide the content within the slot ```div```, when the client side JS is initialised it moves the message outside of this ```div``` and is therefore shown. Test by slowing your network connection to a slow 3g.
**Drawbacks**
Messages will now only be shown to people with JS enabled.
🐿 v2.7.0
=> Hiding the slot container

bower.json, demos/src/demo.scss, main.scss, src/client/bottom-slot.js, src/client/top-slot.js, src/components/anon-subscribe-now-teal/main.scss, src/components/desktop-app-banner/main.scss, src/components/invite-colleagues/main.scss, templates/components/n-alert-banner.html, templates/partials/bottom/b2b-upsell.html
~related: https://github.com/Financial-Times/n-alert-banner/pull/20~
~related: https://github.com/Financial-Times/o-banner/pull/38 going to give the same treatment to `o-banner` and see if origami are happy with it or not.~
The tweaks will ensure that messages render correctly, even if `n-ui-foundations` is not explicitly imported via the app in which `n-messaging-client` is included.
🐿 v2.6.0
=> use n-ui-foundations

src/components/ad-blocker-reg-banner/main.js, src/components/ad-blocker-sub-banner/main.js, src/components/index.js
The ad blocker is now shown via `n-messaging-client` but monitoring is showing that it's being shown more often than the previous implementation. Adding in a bit more logic to better reflect the logic in the previous implementation.
=> Add more ad blocking logic

bower.json, manifest.js, src/client/index.js, src/client/top-slot.js, templates/components/n-alert-banner.html, templates/components/n-messaging-banner.html, templates/partials/top/anon-subscribe-now-teal.html, templates/partials/top/gdpr-consent.html, templates/partials/top/payment-failure.html, templates/partials/top/registration-notice.html, templates/slot.html
Enabled by setting messageSlotTop toggle to 'GdprConsent'
🐿 v2.8.0
=> Support core experience; add GDPR consent message

README.md, critical.scss
This just contains the CSS needed by those message types that can be server-rendered (currently only 'gdprConsent' type
In the consuming app, @import 'n-messaging-client/critical' into the head stylesheet, so it's inlined. Then @import 'n-messaging-client/main' outside the head stylesheet so the full styles are lazily loaded 
This stylesheet outputs only 7Kb of uncompressed CSS vs 47Kb from the existing main stylesheet
🐿 v2.8.0
=> Add an alternative, much smaller main SASS include

src/client/bottom-slot.js, src/client/top-slot.js, src/client/utils.js
Fire both existing events and a new type of event so that we can
migrate other parts of the stack without breaking
🐿 v2.8.0
=> Migrate to our own category of namespaced events

main.scss
As the styles were in both critical and main stylesheets, the CSS build was deduping them and leaving only a copy in the (lazily loaded) main stylesheet. As the markup was server-rendered, this was causing a flash of unstyled content.
🐿 v2.8.0
=> Remove privacy policy styles from main stylesheet as already in critical

src/components/cookie-consent/main.js
Previously if the cookie banner was shown in error, it would
briefly be rendered on the page before being hidden.
This tweaks the done() callback in the cookie custom setup to
return { skip: true } if we do not want to render the message.
This has the benefit of allowing us to track incorrect message
allocataions.
🐿 v2.8.0
=> Small tweak to use the "skip" functionality for cookie banner

manifest.js, src/client/bottom-slot.js, src/components/cookie-consent/main.scss, src/components/index.js, templates/components/n-messaging-banner.html, templates/partials/bottom/cookie-consent.html
- Add variant C of banner
- Make variant A use variant B's styling
- fix an issue with the bottom slot / messaging banner where declarative attributes weren't being used by o-banner
=> Cookie banner variant c

secret-squirrel.js, templates/partials/top/usa-sale.html
🐿 v2.9.0
Update copy and link for USA sale on top banner
https://trello.com/c/wdFghfoE
=> update copy and link on USA sale

manifest.js, src/components/bottom/swg-entitlements-prompt/main.js
I've changed this to use `async` `await` to make it clearer what needs to be awaited.
I believe the main issue was that the function was not returning a promise so the caller moved on. This could of been fixed by adding `return` in front of `swgLoader({ customOnwardJourney: true })`. Async functions always return a promise.
=> Awaiting results of the entitlements call

src/components/bottom/swg-entitlements-prompt/main.js
We only care if they have entitlements, so we prompt them to login
🐿 v2.9.0
=> Remove granted check

test/smoke.js
🐿 v2.10.3
Whilst yak-shaving on another issue on this repo yesterday i noticed the list of features for pa11y testing was hardcoded. As this list changes pretty frequently and the tests are somewhat tucked away (i.e. easy to forget to update) I thought it would be better to generate the list dynamically from the manifest which _should_ be representative of reality
=> dynamically generate list of messages for testing

src/components/bottom/cookie-consent/main.scss
🐿 v2.10.3
The "cookies" link in the cookie banner had the wrong right padding
=> Fix cookie banner link style

src/client/bottom-slot.js
Tackles errors seen in sentry in cases where `guruResult` doesn't exist or no arguments are passed to `imperativeOptions()`
🐿 v2.10.2
=> Tackles errors in sentry

main.scss, manifest.js, src/components/bottom/tech-scroll-asia/main.scss, templates/components/n-messaging-banner.html, templates/partials/bottom/tech-scroll-asia.html
Envoy is working with the Conversion team to create an on-site message to promote the new newsletter with Nikkei, Tech Scroll Asia.
I've added the on-site message for the bottom slot according to other OSMs found in the repo: adding the HTML, the SCSS, and putting the name on the manifest.
I've also added the `compact` theme from `o-banner` which can now be used for future OSMs in `n-messaging-client`.
Please let me know if there are any questions or changes that need to be made.
=> Tech Scroll Asia

src/components/bottom/brexit/main.scss, src/components/bottom/tech-scroll-asia/main.scss, templates/partials/bottom/brexit.html, templates/partials/bottom/tech-scroll-asia.html
It appears that with the new version of n-gage the build is failing due to _verify_stylelint selector-class-pattern
So I have made some changes to prevent that. Please check to see if the banners are correct
Brexit:
Tech Scoll Asia:
🐿 v2.12.3
=> Removes classes .variant-brexitCampaign and variant-techScrollAsia

manifest.js, secret-squirrel.js
Reverts Financial-Times/n-messaging-client#142 for this ticket: https://trello.com/c/bohGY4xk/1095-05-marketing-popup-prompt-lionel-slider-link-update
=> Revert "Update offer ID on marketing pop prompt"

README.md
This is to avoid the issues that I had along with other devs from my team when trying to commit to the repo. While consumer products devs may all have ES Lint and Editor Config, not every team does, so clarifying that these are needed to be able to see errors when contributing is very helpful.
Additional changes have been made to the n-gage repo to make seeing and fixing linting errors easier.
=> Update docs to include info about linting

templates/partials/bottom/app-promo-mobile.html
🐿 v2.12.3
- Tracking params `class=“n-messaging-banner__link” data-n-messaging-banner-action=“” data-trackable=“onsite-message-link”`  added to the onsite messageId  `appPromoMobile`
=> Tracking Params added to the onsite message app download link

templates/partials/bottom/app-promo-mobile.html
🐿 v2.12.3
- Onsite message, ID `appPromoMobile` downloads links , `border bottom` style updated.
=> Remove border bottom style from the download links

templates/partials/bottom/app-promo-mobile.html
🐿 v2.12.3
- Tracking code is added to the Download link for both `google play` and `Apple store`
- Google play download link corrected.
=> Tracking code added to the Download links, message ID , appPromoMobile.

bower.json, src/components/bottom/team-trial/main.js, src/components/bottom/team-trial/main.scss
Many components require o-loading and to allow us to upgrade them
o-loading has to be on v3.
🐿 v2.12.3
=> Upgrade o-loading to a newer version

templates/partials/bottom/b2b-trial-mobile.html
By default anchor tags within `n-messaging-banner__action` don't include
tracking events. Adding these data attributes enables `n-messaging:act`
events for the new app promoting banner for the b2b trial onboarding journey.
🐿 v2.12.3
=> Adds data attrs to enable tracking on act buttons

manifest.js, templates/partials/top/nbe-auto-sub.html
This is a new messaging component for our Envoy journey - NBE auto subscription - which automatically signs up B2B triallists to 3 newsletters, unless they opt out by acting on this alert banner.
It's fairly simple, just the neutral Origami alert banner in the top slot, so I think this is everything: create partial and add it to the manifest.
=> NBE auto subscription message alert banner

manifest.js, templates/partials/bottom/daily-digest.html
🐿 v2.12.4
This is to support the new Envoy journey 'Predicted to Disengage - NBA'.  For users that have a change in their rfv such that they cross a certain threshold are predicted to disengage, Envoy will present a series of onsite messages designed to re-engage them.  Invititation to subscribe Daily Digest is one of these.  The other OSMs are already implemented and were used in the similar journey, NBA (test).
Presenting a simply link to the Alerts page is not the ideal UX, but is expedient and allows us to put the journey live soon.
The ideal CTA would have been a button on the OSM to subscribe the user directly to Daily Digest but...
.... this is not currently straightforward to implement because the html would need to incorporate a form rather than a simply link, AND would need to …
=> Add new OSM.  Link to Daily Digest subscribe page

templates/components/n-alert-banner.html
This was confusing for users of voice activation software as it looks like a button but behaved like a link.
[Trello ticket](https://trello.com/c/RvFGcUpz/143-dacelementroleissue1)
=> A11y: Make buttons have role="button"

README.md
Beacon and Keen are no longer used by FT.com:
`We've had to delete it because Keen (the underlying third-party data store) are raising prices dramatically in December 2018.`
This link now redirects to https://customer-products.in.ft.com/wiki/Beacon-and-Keen with the above message so removing it from the README in this PR.
=> Remove Beacon monitoring link

manifest.js, src/components/top/new-agenda/main.scss, templates/partials/top/new-agenda-paywall-freeze.html
🐿 v2.12.4
Paywall Freeze Banner that will get displayed for 1 day during the New Agenda campaign.
Also renamed the existing campaign banner to match tracking naming conventions.
=> Add new agenda paywall freeze banner

src/components/top/myft-disengaged-tooltip/main.js
add missing space
instead of `read the latestbing, bang and bong stories` display `read the latest bing, bang and bong stories`
=> fixes myft disengaged tooltip spacing when followers > 0

templates/partials/bottom/abb-licence.html
🐿 v2.12.4
While we're testing to make sure this doesn't display to everyone again, forcibly hide the message so it's there in the markup and we can verify it's working as intended.
=> Hide ABB licence message for the moment

templates/partials/bottom/abb-licence.html
Reverts Financial-Times/n-messaging-client#186
Tested this and it appears to be working as expected. Re-showing the message.
=> Revert "Hide ABB licence message for the moment"

src/components/top/myft-disengaged-tooltip/main.js
if document.referrer is blank (i.e refresh or bookmark), don't show the myft header tooltip
=> dont show myft header tooltip on refresh

src/components/top/myft-disengaged-tooltip/main.js
disable myft disengaged tooltip earlier to prevent unnecessary calls …to myft-proxy 🐿 v2.12.5
=> disable myft disengaged tooltip earlier

manifest.js, templates/partials/bottom/bcg-licence.html
🐿 v2.12.4
[Trello card](https://trello.com/c/FbhyMvZD/1594-bespoke-onsite-message-for-boston-consulting-group)
This is mostly a carbon copy of the ABB licence work that was done previously which is no longer needed (hence all the renaming).
Dependent on https://github.com/Financial-Times/next-ammit-api/pull/594
=> Add BCG message

manifest.js, package.json, src/components/bottom/ft-weekend-promo/main.js, templates/partials/bottom/ft-weekend-promo.html
Caters for a scenario not encountered before, where the CTA destination of an OSM is another page set up to display the same OSM.  In this case, the Spoor/Envoy pipeline does not react quickly enough to register a user action and therefore dismiss the message before the next page is rendered (and the message already re-displayed).
Storing OSM state and rules in the browser allows us to prevent this poor user experience.
This PR is a first pass to get us going quickly with ftWeekendPromo, and test this in production for a single message.  If successful, the intention is to extract the new functionality to be easily reusable by other messages.
NB.  A subsequent is also ready for view, and if you don't think it's too risky.. we could just go straight to this one instead, which is generic and …
=> First pass 🐿 v2.12.5

src/components/bottom/app-promo-mobile/main.scss
This PR is about to fix the css issue reside in appPromoMobile messages.
=> Fix text overlap on image on appPrommoMobile message 🐿 v2.12.5

main.scss, manifest.js, src/components/bottom/my-ft-feedpage-overview/main.scss
New message for use by Envoy team in a new journey, to test NBA models against each other. 
(see https://docs.google.com/presentation/d/1Cd9pvhmrnYZLhV0v9I9YmYXLno0l_hb7mfNkUk_e2dE/edit#slide=id.g50dea84098_0_0)
This is the ticket for creating the message:  https://trello.com/c/6UZygtZL/609-nba-a-b-test-build-myft-feedpage-on-site-message
Relies on the dynamic content provided by messaging-guru:  https://github.com/Financial-Times/next-messaging-guru/pull/60
Mocked up images here from the design team: 
Screenshot of the message rendered by n-messaging-client running locally:
=> New message: myFtFeedpageOverview 🐿 v2.12.5

critical.scss
Currently, theres a bug on next-article where the payment error message and the NBE banner (both relying on default oMessage styling) aren't receiving the default styles. I have replicated this locally.
Although the documentation (and the code) looks to automatically include all message states if you pass in "all" - on article this does not seem to be the case. This PR explicitly adds in the error and neutral states which outputs the required CSS
=> fix: explicitly include banner styles

package.json, src/client/utils.js
It's a major version behind and the Snyk report for dependent projects
is fretting about possible vulnerabilities. It's only used to get and
set properties in one place so let's not use lodash here.
=> Remove lodash.

src/client/bottom-slot.js
Bottom banners did not have the class applied which gives them the
correct z-index for notifications. This adds the class manually for
imperative banners 🐿 v2.12.5
=> Fix a z-index issue with bottom banners

templates/components/o-message.html
Currently if a banner title exists, it is used as the alt text for the banner image. This may cause issues for screen reader users because the image is placed next to the text so the message is announced twice.
Also, the text itself doesn't convey meaningful information about the image.
DAC ticket: https://trello.com/c/i2TjYybE/154-decorative-image-with-alt-issue-id-dacdecorativeimage01
=> Remove alt text for banner images

src/client/bottom-slot.js
Adds a missing `.default` to the oBanner require statement in n-messaging-client to resolve an ES6/CJM interoperability error.
`o-banner` is exported as a default so it will need to be imported using this syntax. https://github.com/Financial-Times/o-banner/blob/master/main.js#L11 
In Page Kit apps, this causes a `TypeError: oBanner.getOptionsFromDom is not a function` error to thrown when initialising n-messaging-client (which refers to [this line](https://github.com/Financial-Times/n-messaging-client/blob/master/src/client/bottom-slot.js#L18) in the same file)
n-messaging-client is currently required by next-front-page, next-stream-page and next-article but there are no errors in production for these apps because n-ui contains a hack which lets it resolve the current require statement.
=> Adds .default to the o-banner require statement, resolving ES6/CJM errors

manifest.js, secret-squirrel.js, src/client/utils.js
[Ticket](https://trello.com/c/RzsC1lm7/1734-update-offerid-for-25-marketing-prompt)
Related PR that adds the discount copy for this offer: https://github.com/Financial-Times/next-signup-api/pull/276
=> Add 25% offer id related to the priceIncreaseTest2020 work

manifest.js, secret-squirrel.js
Exactly the same as https://github.com/Financial-Times/n-messaging-client/pull/231, but for non-page-kit apps like Front Page, Stream Page, and Articles.
=> Add 25% offer id related to the priceIncreaseTest2020 work 🐿 v2.12.5

Makefile, src/presenters/slot-presenter.js
For some reason, handlebars was calling the presenter (I was able to get
a breakpoint to catch inside the getters) but wasn't receiving the value
being returned. Eventually came to the realisation that these don't need
to be getters at all as far as we could tell so just setting them as
static properties.
🐿 v2.12.5
=> Remove unnecessary getters from slot presenter.

src/client/bottom-slot.js
This is temporary. As it stands, the require with `default` works in `next-article` and `next-stream-page` but not `next-front-page`. This will make it work everywhere without having to do an overhaul of front-page.
🐿 v2.12.5
And yes... I know:
=> Monkey patch o-banner import

src/client/bottom-slot.js, src/client/top-slot.js
When a view event is fired from n-messaging-client we have no way of knowing the dynamic content that the message contained. This is ok when the messages are static and the contents remains the same but doesn't work for dynamic messages with changing content.
As an example, if we're pushing topic recommendations into a message, these could be different for each user. We need to be able to see which topics were present when a user views the message.
For now, we're making use of the `messaging_variant` field that is already present in the tracking events and used by the analytics team. By default, this field contains the message name -
This change allows `messaging_variant` to contain a string that explains the dynamic content contained in the message. e.g
🐿 v2.12.5
=> Adds ability to track dynamic content in OSMs

client/components/bottom/coronavirus-newsletter-promo/main.scss, client/themes.scss, main.scss, manifest.js, server/templates/components/o-banner.html, server/templates/partials/bottom/coronavirus-newsletter-promo.html
This is identical to the existing Tech Scroll Asia promotion message, with the following changes:
- copy (text)
- newsletter ID in link (coronovirus's instead of Tech Scroll Asia's)
- styling (use slate/lemon colours instead of Tech Scroll Asia's
custom styling)
Desktop:
Mobile:
=> A new coronavirus newsletter promotion

client/components/o-message-notice.scss, server/templates/components/o-message-notice.html
The `img` tag wasn't full height on Firefox. This fixes the issue.
=> Fix vertical align of img tag for cross browser compatibility 🐿 v2.12.5

client/components/top/myft-disengaged-tooltip/main.js, package.json
myFT tooltip AB test for disengaged users was successful.
We are going to roll this out to 100% of users who fall into the predicted to disengage cohort.
However, the tooltip which encouraged users to visit myFT feed was not conclusive, we will not be rolling this out.
[Jira ticket](https://financialtimes.atlassian.net/browse/CON-130)
**Release** 👇 
The tooltip is displayed for users who fill **All** the requirements below
- Users who are in disengaged cohort
- Users who haven't followed any topics
- Users who haven't seen the tooltip more than 3 times
**Kill** 👇 
The tooltip was displayed for users who filled **All** the requirements below
- Users who are in disengaged cohort
- Users who visit articles via non-ft site
- Users who have followed concepts
- Users who haven't seen the …
=> Make myFT disengaged tooltip as a permanent feature

server/templates/components/o-message-notice.html
Before
After
Mobile hasn't changed
=> Add possessive apostrophe to days 🐿 v2.12.5

client/components/bottom/marketing-popup-prompt/main.js, manifest.js, server/templates/partials/bottom/marketing-popup-prompt.html
Ammit doesn't use messaging data for unregistered users. Marketing Popup Prompt doesn't hide for 10 days after showing as a result. This PR uses a cookie with 10 day expiry to dismiss the notice instead of using Ammit.
The implementation is quite straight forward and doesn't add complexity to the Ammit code.
A user won't see lower priority messages instead of popup prompt when it is hidden because Ammit doesn't know that it is being hidden.
Start of Ammit modification solution: https://github.com/Financial-Times/next-ammit-api/pull/671
=> ACQ-239 Use cookie to show or hide marketing popup prompt message

client/components/bottom/marketing-popup-prompt/main.js, secret-squirrel.js
Original behaviour was to hide the marketing pop up prompt after it has been shown once, regardless of user interaction.
This PR changes the behaviour so the cookie hiding the prompt is only dropped when the user dismisses the prompt.
=> ACQ-239 Drop popup prompt cookie only when dismiss button clicked

server/templates/partials/bottom/cookie-consent.html
This ads text to indicate to users that the "cookies" link on the cookie consent popup opens in a new window
=> add accessibility text for cookie consent links 🐿 v2.13.0

README.md, bower.json
Jira card: https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1051&modal=detail&selectedIssue=CPP-89.
This PR upgrades the version of its `n-ui-foundations` bower dependency.
It also upgrades the version of its `n-myft-ui` bower dependency to a version that uses the same `n-ui-foundations` version (v6.0.0), as it too has a dependency on that package.
I have also updated the README as I was confused for a while trying to get the messaging components to appear and didn't immediately realise you needed to turn them on in toggler.
=> Update n-ui-foundations ^4.0.0 -> ^6.0.0

client/bottom-slot.js, client/utils.js
The remaining articles bottom slot message has different tracking context depending on the response from messaging guru.
This PR looks for a `trackingContext` key in the barrier guru response and adds it to the configuration tracking context if it exists. This allows for dynamic tracking events to be generated.
An example implementation in messaging guru is here: https://github.com/Financial-Times/next-messaging-guru/pull/96
=> ACQ-279 Remaining articles tracking

client/components/bottom/remaining-articles/main.js
Users will see a final 'This is your last article' message before being shown the paywall.
This changes the message to show only when there are fewer than 0 articles left instead of fewer than 1.
=> Change conditional to hide message when less than 0 remaining 🐿 v2.13.0

server/templates/components/o-banner.html, server/templates/partials/bottom/app-promo-mobile.html, server/templates/partials/bottom/b2b-trial-contact-us.html, server/templates/partials/bottom/b2b-trial-mobile.html, server/templates/partials/bottom/book-your-consult.html, server/templates/partials/bottom/content-message.html, server/templates/partials/bottom/coronavirus-newsletter-promo.html, server/templates/partials/bottom/daily-digest.html, server/templates/partials/bottom/fast-ft.html, server/templates/partials/bottom/markets-data.html, server/templates/partials/bottom/onboarding-myft.html, server/templates/partials/bottom/onboarding-premium.html, server/templates/partials/bottom/oneclick-daily-digest.html, server/templates/partials/bottom/secondary-school-survey.html, server/templates/partials/bottom/tbyb-in-trial-subscribe.html, server/templates/partials/bottom/tbyb-post-trial-subscribe.html, server/templates/partials/bottom/tech-scroll-asia.html, server/templates/partials/bottom/us-election-2020-promo.html
The `close-button-label` option will be passed through to o-banner if a `closeLabel` parameter exists.
This will improve the accessibility of the close button as screen reader users will be given the context they need to decide if they want to close the banner.
I have added a close label to each banner, I am new to most of these banners so I have tried to use my best judgement for the wording but I am open to better suggestions
=> Improve the accessibility of the close button on banners - NOPS-257

README.md, client/top-slot.js
`n-messaging-client` is able to lazy load messages. This works for the bottom slot with examples in production. It looks like lazy loaded top slot messages haven't been used for a while and aren't working.
When trying to lazy load a message in the top slot nothing is rendered, only the placeholder template shows. This pull request fixes the client logic to check whether the message should be lazy loaded or not when deciding how to render using `o-message`. It also adds parameters passed to `o-message` to allow the message to load and attach to the correct parent element.
I imagine the logic can be simplified further to reflect how bottom slot messages are loaded. This is an initial fix.
=> ACQ-342 Check whether message is lazy loaded when setting declarativeElement

client/components/top/try-full-access/main.scss
**Summary:**
- increase the padding below the button on screens S && XS
- decrease the padding above the button on screens S && XS
- alight the button with the bottom of the second row on screens larger than M incl.
**Screenshots:** 
S                        | M
=> ACQ-342 Tweak `Try Full Access` message styles.

client/top-slot.js
Errors are currently being thrown on front-page:
```
/__assets/hashed/page-kit/n-messaging-client.784e097f3c9c.bundle.js:1 Error: *** o-message error:
Messages require a type. Available types are:
- action
- alert
- notice
***
at s (/__assets/hashed/page-kit/o-message.f00f50548094.bundle.js:1)
at t.value (/__assets/hashed/page-kit/o-message.f00f50548094.bundle.js:1)
at new t (/__assets/hashed/page-kit/o-message.f00f50548094.bundle.js:1)
at e.exports (/__assets/hashed/page-kit/n-messaging-client.784e097f3c9c.bundle.js:1)
at async Promise.all (/index 0)
```
=> fix: provide fallback o-message type 🐿 v2.12.5

client/top-slot.js, package.json, server/templates/components/o-message.html
The latest o-message will lazily construct a message if the parentElement is specified - even if there is already an element declared. This lead to the message being constructed inside the already defined message. As such:
`o-message` code:
```
if (this.opts.parentElement || !(this.messageElement instanceof HTMLElement)) {
this.messageElement = construct.message(this.opts);
// attach oMessage to specified parentElement or default to document body
const element = this.opts.parentElement ? document.querySelector(this.opts.parentElement) : document.body;
element.appendChild(this.messageElement);
}
```
This updates the code to only specify `parentElement` if the message is lazy loaded.
Fix:
=> fix: don't provide parent element if message is NOT lazy

server/templates/partials/top/payment-failure.html
With the new MMA and retirement of the old route, links that point to the old route need to be updated. This is one of them.
=> ACC-654 Update URL pointing to Billing Details

client/components/top/try-full-access/main.scss
According to https://github.com/Financial-Times/o-grid/blob/master/src/scss/_variables.scss#L51 `XS` breakpoint doesn't exist and is causing the build of `next-front-page` to fail
=> [ACQ-605] Replace invalid XS breakpint with S

client/components/top/us-election-poll-tracker/main.scss, main.scss, manifest.js, server/templates/partials/top/us-election-poll-tracker.html
To test locally, run `make install` then `make demo-watch`.
Go to https://toggler.ft.com/#messageSlotTop and select the `us-election-poll-tracker` variant.
This PR adds a top slot promotion for the US Poll Tracker
| Mobile | Desktop |
| ------ | ----- |
|![image](https://user-images.githubusercontent.com/25018001/96700320-383d8280-1387-11eb-848a-d3d59c2c5d68.png)|![image](https://user-images.githubusercontent.com/25018001/96700356-4390ae00-1387-11eb-821a-50a5946453f3.png)|
[ticket](https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1128&projectKey=UG&modal=detail&selectedIssue=UG-308)
=> ug-308/add us-election-poll-tracker to messageSlotTop

client/components/top/us-election-week-discount/main.scss
- Improve the styles so the background is end to end on smaller resolutions
- Use `max-width` instead of `width` for the main part of the banner
This is the result of really narrow displays which adds a horizontal scroll...
=> Improve election week discount banners

client/components/top/us-election-week-discount/main.scss
https://financialtimes.atlassian.net/browse/ACQ-655
The large banner is now vertically centered
Before:
After:
=> ACQ-655 Align large banner vertically

client/components/top/three-months-intro-price-promo/main.scss, client/components/top/try-full-access/main.scss
Applies for `TryFullAccess` and `ThreeMonthsIntroPricePromo` banners.
=> [ACQ-433] Add border-bottom: 1px solid paper to slate top messages

server/templates/partials/bottom/cookie-consent.html
This week we launched the new Manage Cookies page. Among the changes it brought 
was the inclusion of the main header and footer (previously only a plain logo 
was rendered on non-whitelabel pages).
In production it transpired that because the "manage cookies" link in the cookie 
banner points to https://**cookies**.ft.com/preferences/manage-cookies,
all navigation links were broken (because the URLs are relative).
See https://financialtimes.atlassian.net/browse/NOPS-634
(The old app side-stepped this issue by rendering an inert logo instead of the 
main navigation and omitting the footer entirely, which has been our stop-gap 
fix too)
Changing the subdomain to 'www' when linking to 
`https://www.ft.com/preferences/manage-cookies` will allow us to render the 
standard header and footer …
=> Fix navigation on new Manage Cookies page

critical.scss, manifest.js
We'd like to add a new message to the top of the [Climate Capital page](https://ft.com/climate-capital) to capture user feedback. The message is generated by `next-messaging-guru` (details [are in this PR](https://github.com/Financial-Times/next-messaging-guru/pull/124)), but a couple of minor tweaks are required here to add support for the 'notice' `o-message` type and to add the new message to the manifest.
Design specs for the message [are in this ticket](https://financialtimes.atlassian.net/browse/CON-408).
Content specs [are in this ticket](https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1211&modal=detail&selectedIssue=CON-460).
=> CON-460 Add Climate Capital Feedback Message

.circleci/config.yml, .github/settings.yml, README.md
[Ticket CPP-442 Upgrade GitHub repos from `master` to `main`](https://financialtimes.atlassian.net/browse/CPP-442)<br/><br/>As an organisation we are moving away from the usage of `master` as a central branch and switching it to `main`, this is to avoid using unnecessary language that can be offensive. This PR is for making those changes. <br/><br/>This PR was created using a nori script<br/><br/>_Nori is a command-line application for managing changes across multiple (usually Github) repositories._
=> CPP-442 Upgrade GitHub repos from master to main

server/templates/partials/bottom/cookie-consent.html
This PR makes two changes:
1. Using a relative link makes it easier to test user journeys locally
2. It restores the `redirect` query parameter mentioned in [this discussion](Financial-Times/o-cookie-message#145 (comment)) allowing users to navigate back to the page on which they were shown the cookie banner
=> Make manage cookies link more flexible and informative

bower.json, package-lock.json, package.json, scripts/fromBowerToNpm.js
This package forces team to use Bower, with this PR we introduce the necessary packages in NPM so consumers can use the library without Bower.
To be sure that npm packages are kept in sync with Bower packages a preinstall hook modify package.json with the Bower packages, if some of them do not have been mapped in the script it throws an error.
(documentation already stays that the package can be installed through npm / bower, so no updates in docs have to be done)
=> Bower and npm compatible package

.circleci/config.yml
This is a pull request to clear the Circle CI cache as the nightly builds were failing to install some dependencies.
=> bumped circle cache keys to version 3 to clear cache

.circleci/config.yml
currently the npm cache is for all branches. Nightly builds are broken after trying to use the cache saved by renovate-circleci-node-15.x. This PR is to split out the cache on a per branch basis.
=> changes cache keys to be branch-specific

manifest.js, package-lock.json, server/templates/partials/top/renew-single-term-banner.html
Single Term users are user who are not on a subscription that auto renews. What this means, their subscription can expire. We want to encourage them to renew their subscription when that happens so we are adding a Top banner to FT pages. 
https://financialtimes.atlassian.net/browse/ACC-1003
Yes, it looks a bit weird, but unless we release this and the changes in Ammit, this is the best I have for a screenshot
**oops, the button should say Renew, but you get the idea**
=> ACC-1003 Add Top Banner for Single Term Renew message

client/components/top/digital-marketing-sept-apac/main.scss, client/components/top/digital-marketing-sept-row/main.scss, main.scss, manifest.js, secret-squirrel.cjs, server/templates/partials/top/digital-marketing-sept-apac.html, server/templates/partials/top/digital-marketing-sept-row.html
`PR in DRAFT until Product team confirm the CTA action URLs`
Marketing September Campaign:
2 new versions of the slider:
- APAC region - XX% would read 33%
- All other regions - XX% would read 50%
Designs: https://www.figma.com/file/aEiiMtHu2qgOzHS118CzF4/Letters-to-this-New-World?node-id=9%3A18
How to test:
- Select the variant from: https://toggler.ft.com/#messageSlotTop
- https://local.ft.com:5005/
https://financialtimes.atlassian.net/browse/ACQ-1123
| Desktop | Mobile |
|---|---|
| ![image](https://user-images.githubusercontent.com/13876273/131319692-748a8c19-2c73-402c-8835-fb0e5cd11fd7.png) | ![image](https://user-images.githubusercontent.com/13876273/131320274-d3523fc9-dedc-42b3-b2cf-6c3188181b46.png) |
| ![image](https://user-images.githubusercontent.com/13876273/131320568-1d460b00- …
=> ACQ-1123: Top slot changes for Sept Campaign

.circleci/config.yml
We need teams to migrate their CircleCI pipelines to use the newly created "npm-publish-token" context, so that we can revoke all of the old untrusted tokens.
=> add npm-publish-token context to circleci config

server/templates/partials/bottom/embedded-onboarding.html
Removes an unclosed div tag on the message template that was breaking the layout of the message's consumer.
=> UG-842: Remove dangling tag from embeddedOnboarding template

package-lock.json, package.json
update next-myft-client to 7.13.0 to fix this issue with the installation:
```
npm ERR! code 1
npm ERR! path /Users/kote/FT/n-messaging-client/node_modules/next-myft-client
npm ERR! command failed
npm ERR! command sh -c ([ "$INIT_CWD" != "$PWD" ] || npm_config_yes=true npx check-engine); npx npm-force-resolutions
npm ERR! Error: ENOENT: no such file or directory, open './package-lock.json'
npm ERR!     at Object.openSync (node:fs:585:3)
npm ERR!     at Object.fs [as readFileSync] (node:fs:453:35)
npm ERR!     at npm_force_resolutions$core$node_slurp (/Users/kote/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:15:20)
npm ERR!     at npm_force_resolutions$core$read_json (/Users/kote/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolution …
```
=> update next-myft-client to solve issue on dependency installation

server/templates/partials/bottom/content-message-danske-bank.html
fix a typo for accesibility purposes in the Danske Bank message.
=> ACC1627 - fix typo Danske Bank message

client/components/top/myft-disengaged-tooltip/main.js
One of the components in myft-disengaged-tooltip had reference to 'next-myft-client/myft-bower'. 
With the removal of bower components, 'next-myft-client/myft-bower' is not compiled anymore.
Therefore, this file has been replaced to use 'next-myft-client/myft-npm
Figure 1: Compilation successful
'
Figure 2: Output
=> myftclient to use npm replacing bower

client/components/bottom/academia-cta/main.js, client/components/bottom/academia-cta/main.scss
made design tweaks for the academiaCTA message.
| Before | After |
| ------ | ----- |
| <img width="1440" alt="Screenshot 2022-06-23 at 15 51 33" src="https://user-images.githubusercontent.com/64967358/175331337-95dfe15d-b63b-4244-8d90-a0822facf6a4.png">|  <img width="1440" alt="Screenshot 2022-06-23 at 15 51 46" src="https://user-images.githubusercontent.com/64967358/175331706-21107d8c-3997-4535-9938-23d26b8591b4.png">     |
https://financialtimes.atlassian.net/browse/UG-911
=> Make tweaks to academia cta message

server/templates/partials/bottom/cookie-consent.html
This copy change has been approved by compliance and is needed to support an Ads use case with Permutive Vault.
[Jira ticket](https://financialtimes.atlassian.net/jira/software/c/projects/FPD/boards/1480?modal=detail&selectedIssue=FPD-68)
=> Updates cookie message copy

package-lock.json, package.json
This PR is to fix an issue in [[ADSDEV] Cookie Banner fixes](https://github.com/Financial-Times/n-messaging-client/pull/474), which incorrectly bumped the version of `o-cookie-message` in devDependency rather than peerDependency.
JIRA ticket: https://financialtimes.atlassian.net/browse/ADSDEV-1231
Origami PR for `o-cookie-message`: https://github.com/Financial-Times/origami/pull/867
=> ADSDEV-1231 fix on cookie banner release

.circleci/config.yml, Makefile, package-lock.json, package.json
Automatically ran via Platforms' [migration script](https://github.com/Financial-Times/platform-scripts/blob/464d56876a27742dbdee2713a31266cc268ebfe3/upgrade-node-18/upgrade-node-18.ts)
=> Update to Node 18

package-lock.json, package.json
next-myft-client is using an insecure FT_Session token.
FT Core are switching off the insecure sessions. ([Slack Thread](https://financialtimes.slack.com/archives/C042NBBTM/p1702907414857149))
We want to have a clean tree with updated next-myft-client and this app is used by next-stream-page and next-myft-page so I believe this needs to be updated even though it is deprecated. 
The changes in version are just: 
- dropping support for node 14 
- Adds support for node 18
- Fix the insecure session thingy
=> Update myft client

client/components/top/cop-digital-acquisition/main.scss, client/components/top/digital-marketing-new-world/main.scss, client/components/top/jan-22-digital-sale-banner/main.scss
The name `brand-ft-pink` is deprecated and causing annoying Sass warnings for projects which include n-messaging-client.
Replace `brand-ft-pink` with `ft-pink`. 
```
/next-home-page/apps/home-page/client/main.scssWarning: The color "brand-ft-pink" is deprecated for your brand's palette, and will be removed in the next major. Replace "brand-ft-pink" with "ft-pink". This is so we can align our naming with our designers, including the Brand team.
node_modules/@financial-times/o-colors/src/scss/_functions.scss 30:3                oColorsByName()
node_modules/@financial-times/n-exponea/styles/digitalMarketingNewWorld.scss 34:13  @import
node_modules/@financial-times/n-exponea/main.scss 8:9                               @import
stdin 83:9 …
```
=> Replace `brand-ft-pink` colour use with `ft-pink`

.circleci/config.yml, .snyk, package-lock.json, package.json
In mid-December 2024 we will be letting our Snyk contract expire. We'll
be moving to GitHub Advanced Security as an alternative.
This PR is an attempt to get ahead of the deadline. Considering how out
of date some of our Snyk implementations are, and that we rarely take
the time to merge the PRs, we think it's fine to remove it way ahead of
time.
If you want an interrim solution, enable Dependabot Security updates for
this repository by visiting the following page and clicking 'Enable' next
to 'Dependabot security updates':
https://github.com/Financial-Times/n-messaging-client/settings/security_analysis
You're also free to ignore this PR and do the work yourself closer to
the deadline. Cyber will be doing some broader comms later in the year.
This PR was automated, please take a little …
=> Remove snyk [automated]
